<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="I2E-LAP-MP03" failures="1" tests="6" name="testCasesV2.TestCasesSprint11_2" time="10.437" errors="0" timestamp="2022-03-01T15:30:23 IST" skipped="0">
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_059" time="0.520"/>
  <system-out/>
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_060" time="2.219"/>
  <system-out/>
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_067" time="0.396"/>
  <system-out/>
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_069" time="0.296"/>
  <system-out/>
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_071_Register" time="0.043"/>
  <system-out/>
  <testcase classname="testCasesV2.TestCasesSprint11_2" name="TLMDRx_070__Register" time="6.963">
    <failure message="The following asserts failed:
	expected [NEX] but found [NEXT]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [NEX] but found [NEXT]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testCasesV2.TestCasesSprint11_2.TLMDRx_070__Register(TestCasesSprint11_2.java:262)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TLMDRx_070__Register -->
  <system-out/>
</testsuite> <!-- testCasesV2.TestCasesSprint11_2 -->
